name: Deployment Pipeline
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

      - name: Clone Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install --immutable --immutable-cache --check-cache

      - name: Lint
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint # will run `yarn lint` command

      - name: Run Test
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: test:ci # will run `yarn test:ci` command

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the nextjs-weather-app Docker image
        env:
          OPENWEATHER_API_BASE_URL: http://api.openweathermap.org
          NEXT_PUBLIC_DEFAULT_CITY: "santiago de chile"
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
        run: |
          docker build -f Dockerfile.production -t ghcr.io/kevin-dev71/nextjs-weather-app:latest .
          docker push ghcr.io/jonashackt/hello-world:latest
